spring:
  config:
    activate:
      on-profile: prod

  datasource-view: # 生产用 Oracle，必须用 jdbc-url
    jdbc-url: jdbc:oracle:thin:@192.168.13.41:1521/JCGW?oracle.jdbc.timezoneAsRegion=false
    username: crbsb
    password: crbsb
    driver-class-name: oracle.jdbc.OracleDriver

  # 可选：生产 hikari 调优
  datasource-view.hikari: # 注意前缀 datasource-view.hikari
    maximum-pool-size: 15
    minimum-idle: 5
    idle-timeout: 300000
    connection-timeout: 20000
    max-lifetime: 1800000
    validation-timeout: 5000

  jackson:
    time-zone: Asia/Shanghai

  jpa:
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Shanghai

logging:
  level:
    root: INFO                    # 或者改成 WARN（更干净）
    org.hibernate.SQL: ERROR      # 关闭 SQL 语句输出（你已经设为 ERROR）
    org.hibernate.orm.jdbc.bind: ERROR   # 关键！关闭 Hibernate 6+ 的绑定参数详细日志
    # 可选：其他常用 Hibernate 日志也一起关掉
    org.hibernate: ERROR
    org.hibernate.type: ERROR
    org.hibernate.orm: ERROR